### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by d6u** [d6u/magic-board#1]
- [x] Increase change life button responsiveness, e.g. increase tap areas
- [x] Redirect non-exist routes to `/`
- [x] Roll from 1 to 6
- [x] Improve "click" event speed on mobile (add touch event)
- [x] Force "100%" page height for mobile
- [x] Enable end games
- [ ] Remove store listener when unmount
- [ ] Clean up database
- [ ] Block players from visiting games they don't belong to
- [ ] Enable navigation to `/` everywhere
- [ ] Resume games from `/`
- [ ] Disconnection handling
- [ ] Initial loading animation
- [ ] Animate transitions
- [ ] Deploy script
